### ISSUE TITLE
Starting Development Server issue

### ISSUE THREAD

**Issue by adityassharma-ss** [cncf/landscape#2920]
I have nodeJS installed locally & when i tried to run it using `./server.js` it threw this error:

events.js:353
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 49.44.79.236:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
Emitted 'error' event on ClientRequest instance at:
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:376:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -4039,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '49.44.79.236',
  port: 443
}
Can someone explain me that why am i getting this and what can i do solve this?

**Comment by Doraemon-520** [comment]
I have the same problem. Have you solved it?

**Comment by Doraemon-520** [comment]
@adityassharma-ss I have the same problem as you. Have you solved it?

**Comment by tegioz** [comment]
Hi!

We've just migrated the [CNCF landscape to v2](https://landscape.cncf.io) and this issue probably no longer applies.

Please feel free to reopen if needed 🙂
