### ISSUE TITLE
Yarn fetch bug

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#504]
yarn fetch shouldn't delete any files until it can complete without missing file errors. To see the bug:

1. In `hosted_logos`, make a copy of an SVG and call it aws.svg.
2. In `landscape.yml` set logo for `Amazon Web Services` to `./hosted_logos/aws.svg`.
3. In `landscape.yml` set logo for `Azure Cloud` to `./hosted_logos/doesnotexist.svg`.

So, you have:
```bash
$ git status -s
 M landscape.yml
?? hosted_logos/aws.svg
```

`git diff` gives you:
```diff
diff --git a/landscape.yml b/landscape.yml
index a82179f..c0a6f98 100644
--- a/landscape.yml
+++ b/landscape.yml
@@ -14,13 +14,13 @@ landscape:
           - item:
             name: Amazon Web Services
             homepage_url: 'https://aws.amazon.com/'
-            logo: 'https://upload.wikimedia.org/wikipedia/commons/9/93/Amazon_Web_Services_Logo.svg'
+            logo: ./hosted_logos/aws.svg
             twitter: 'https://twitter.com/awscloud'
             crunchbase: 'https://www.crunchbase.com/organization/amazon-web-services'
           - item:
             name: Azure Cloud
             homepage_url: 'https://azure.microsoft.com/'
-            logo: 'https://www.datocms-assets.com/2885/1513729661-azure_logo_blue.svg'
+            logo: ./hosted_logos/doesnotexist.svg
             twitter: 'https://twitter.com/Azure'
             crunchbase: 'https://www.crunchbase.com/organization/microsoft'
           - item:
```
Now run `yarn fetch`:
```bash
$ yf
yarn run v1.5.1
$ babel-node tools/addExternalInfo.js && npm run yaml2json && npm run report-bad-images
Running with a level=easy. Settings:
     Use cached crunchbase data: true
     Use cached images data: true
     Use cached twitter data: true
     Use cached github basic stats: true
     Use cached github start dates: true
    
Fetching crunchbase entries
.........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Fetching github entries
..............................................................................................................................................................................................................................................
Fetching start date entries
Fetching images

........*.{ Error: ENOENT: no such file or directory, open './hosted_logos/doesnotexist.svg'
    at Object.fs.openSync (fs.js:667:18)
    at Object.fs.readFileSync (fs.js:572:33)
    at getItemHash (/Users/dan/Dropbox/Documents/dev/landscape/tools/fetchImages.js:79:25)
    at _callee3$ (/Users/dan/Dropbox/Documents/dev/landscape/tools/fetchImages.js:89:18)
    at tryCatch (/Users/dan/Dropbox/Documents/dev/landscape/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/dan/Dropbox/Documents/dev/landscape/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/dan/Dropbox/Documents/dev/landscape/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/Users/dan/Dropbox/Documents/dev/landscape/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/dan/Dropbox/Documents/dev/landscape/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (/Users/dan/Dropbox/Documents/dev/landscape/node_modules/core-js/library/modules/_export.js:35:28)
    at /Users/dan/Dropbox/Documents/dev/landscape/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
    at _bluebird2.default.map.concurrency (/Users/dan/Dropbox/Documents/dev/landscape/tools/fetchImages.js:88:18)
    at tryCatcher (/Users/dan/Dropbox/Documents/dev/landscape/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/Users/dan/Dropbox/Documents/dev/landscape/node_modules/bluebird/js/release/map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (/Users/dan/Dropbox/Documents/dev/landscape/node_modules/bluebird/js/release/promise_array.js:114:31)
    at MappingPromiseArray.init (/Users/dan/Dropbox/Documents/dev/landscape/node_modules/bluebird/js/release/promise_array.js:78:10)
    at MappingPromiseArray._asyncInit (/Users/dan/Dropbox/Documents/dev/landscape/node_modules/bluebird/js/release/map.js:30:10)
    at Async._drainQueue (/Users/dan/Dropbox/Documents/dev/landscape/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/Users/dan/Dropbox/Documents/dev/landscape/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/dan/Dropbox/Documents/dev/landscape/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:763:18)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './hosted_logos/doesnotexist.svg' }

> cncf-interactive-landscape@1.0.0 yaml2json /Users/dan/Dropbox/Documents/dev/landscape
> cp src/lookup.json.default src/lookup.json && babel-node tools/generateJson.js


> cncf-interactive-landscape@1.0.0 report-bad-images /Users/dan/Dropbox/Documents/dev/landscape
> babel-node tools/reportBadImages

✨  Done in 8.17s.
```
Which is fine, it's expected to get an error on `doesnotexist.svg`. But:
```bash
$ git status -s
 M cached_logos/amazon-web-services.svg
 M landscape.yml
```
We've deleted aws.svg from `hosted_logos`.

It would be nice to catch the missing file error and throw a `FATAL ERROR` without changing the file system at all.

**Comment by dankohn** [comment]
In addition, yarn fetch seems to be generating and then deleting spurious cached files. In https://github.com/cncf/landscape/commit/6eab0799b830bca8c6aedad1f9358a230730c603 I changed the Alibaba logo in `hosted_logos` and `yarn fetch` created a `cached_logos/alibaba-cloud-container-service.svg`. Then when I made unrelated changes in `https://github.com/cncf/landscape/commit/8ed50a9f3cb0db6287164a07d63982e41797f7d6` it deleted the same file.

**Comment by dankohn** [comment]
One more example. I changed `ibm-cloud.svg`. Running `yarn fetch` produced:
```sh
$ git status -s
 M cached_logos/ibm-cloud.svg
 M hosted_logos/ibm-cloud.svg
 M processed_landscape.yml
 M src/data.json
?? cached_logos/ibm-cloud-container-service.svg
?? cached_logos/ibm-cloud-functions.svg
?? cached_logos/ibm-cloud-kcsp.svg
?? cached_logos/ibm-cloud-private.svg
```
Running `yarn fetch` again (immediately) produced:
```sh
$ git status -s
 M cached_logos/ibm-cloud.svg
 M hosted_logos/ibm-cloud.svg
 M processed_landscape.yml
 M src/data.json
```
